In [1]:
using CSV
file = "./nyse/Fundamentals with Ratios FINAL/fundementals_with_ratios_training_set.csv"
raw = CSV.read(file);

raw

618×78 DataFrames.DataFrame. Omitted printing of 74 columns
│ Row │ Ticker Symbol │ Period Ending │ Accounts Payable │ Accounts Receivable │
│     │ String⍰       │ String⍰       │ Int64⍰           │ Int64⍰              │
├─────┼───────────────┼───────────────┼──────────────────┼─────────────────────┤
│ 1   │ AAL           │ 31/12/12      │ 3068000000       │ -222000000          │
│ 2   │ AAL           │ 31/12/13      │ 4975000000       │ -93000000           │
│ 3   │ AAP           │ 29/12/12      │ 2409453000       │ -89482000           │
│ 4   │ AAP           │ 28/12/13      │ 2609239000       │ -32428000           │
│ 5   │ AAP           │ 02/01/16      │ 3757085000       │ -21476000           │
│ 6   │ AAPL          │ 28/09/13      │ 36223000000      │ -1949000000         │
│ 7   │ AAPL          │ 24/09/16      │ 59321000000      │ 1044000000          │
│ 8   │ ABBV          │ 31/12/13      │ 6448000000       │ 681000000           │
│ 9   │ ABC           │ 30/09/13      │ 14870635000      │ -2312518000         │
│ 10  │ ABC           │ 30/09/16      │ 24670159000      │ -912724000          │
⋮
│ 608 │ XRX           │ 31/12/12      │ 2654000000       │ 641000000           │
│ 609 │ XRX           │ 31/12/13      │ 2360000000       │ 573000000           │
│ 610 │ XYL           │ 31/12/12      │ 775000000        │ 2000000             │
│ 611 │ XYL           │ 31/12/13      │ 811000000        │ -47000000           │
│ 612 │ YHOO          │ 31/12/12      │ 993306000        │ 34752000            │
│ 613 │ YHOO          │ 31/12/13      │ 1045813000       │ 26199000            │
│ 614 │ YUM           │ 29/12/12      │ 2269000000       │ -18000000           │
│ 615 │ YUM           │ 28/12/13      │ 2194000000       │ -12000000           │
│ 616 │ ZBH           │ 31/12/12      │ 206900000        │ -45500000           │
│ 617 │ ZBH           │ 31/12/13      │ 367500000        │ -74300000           │
│ 618 │ ZTS           │ 31/12/13      │ 1381000000       │ -99000000           │

In [2]:
raw[:,78]

618-element Array{Union{Missing, Float64},1}:
  46.689999
  46.689999
 169.119995
 169.119995
 169.119995
 115.82    
 115.82    
  62.619999
  78.190002
  78.190002
  38.41    
  38.41    
 102.949997
   ⋮       
  57.73    
   8.73    
   8.73    
  49.52    
  49.52    
  38.669998
  38.669998
  63.330002
  63.330002
 103.199997
 103.199997
  53.529999

In [3]:
A = []

for i in 3:76
    push!(A, raw[:,i])
end

A

74-element Array{Any,1}:
 Union{Missing, Int64}[3068000000, 4975000000, 2409453000, 2609239000, 3757085000, 36223000000, 59321000000, 6448000000, 14870635000, 24670159000  …  2360000000, 775000000, 811000000, 993306000, 1045813000, 2269000000, 2194000000, 206900000, 367500000, 1381000000]        
 Union{Missing, Int64}[-222000000, -93000000, -89482000, -32428000, -21476000, -1949000000, 1044000000, 681000000, -2312518000, -912724000  …  573000000, 2000000, -47000000, 34752000, 26199000, -18000000, -12000000, -45500000, -74300000, -99000000]                        
 Union{Missing, Int64}[-1961000000, -2723000000, 600000, 2698000, -7484000, 1156000000, 1348000000, -54000000, -44000, 5048000  …  0, 0, -10000000, 4647839000, 123307000, 0, 0, 15600000, 9600000, 9000000]                                                                    
 Union{Missing, Int64}[23, 67, 32, 26, 19, 30, 36, 92, 19, 67  …  9, 14, 10, 27, 10, 74, 50, 13, 12, 54]                                                    

In [4]:
B = zeros(length(A),length(A[1]))

for i in 1:length(A)
    for j in 1:length(A[i])
        B[i,j] = A[i][j]
    end
end

In [5]:
B = B'
B

618×74 LinearAlgebra.Adjoint{Float64,Array{Float64,2}}:
 3.068e9     -2.22e8          -1.961e9    …  2.4855e10   -3.67e8      -5.6 
 4.975e9     -9.3e7           -2.723e9       2.6743e10    0.0        -11.25
 2.40945e9   -8.9482e7    600000.0           6.205e9     -2.7095e7     5.29
 2.60924e9   -3.2428e7         2.698e6       6.49381e9   -1.0789e8     5.36
 3.75709e9   -2.1476e7        -7.484e6       9.73702e9   -1.19709e8    6.45
 3.6223e10   -1.949e9          1.156e9    …  1.71e11      0.0         40.03
 5.9321e10    1.044e9          1.348e9       2.16e11      0.0          8.35
 6.448e9      6.81e8          -5.4e7         1.879e10    -3.2e8        2.58
 1.48706e10  -2.31252e9   -44000.0           8.79592e10  -1.51686e9    1.88
 2.46702e10  -9.12724e8        5.048e6       1.47e11     -4.39601e9    6.73
 1.0889e10    3.6e7           -1.26e9     …  1.905e10    -5.591e9      3.76
 5.948e9     -1.13e8           5.3e7         1.9657e10   -6.844e9      1.64
 7.29257e8    3.3649e7    926000

In [6]:
prices = raw[:78]
shares = raw[:77]

mkt_cap = prices.*shares
y = mkt_cap

618-element Array{Float64,1}:
 1.5641149665e10      
 7.611507391495777e9  
 1.239371426576783e10 
 1.2360841603946102e10
 1.2412568588116007e10
 1.07160263303394e11  
 6.337087832349199e11 
 1.001919984e11       
 1.8038059150222427e10
 1.6589862019528402e10
 6.0914582434549995e10
 6.0331804865869995e10
 5.147233599688258e10 
 ⋮                    
 8.218652729372e9     
 1.159150000194e10    
 1.087964516007e10    
 9.19215e9            
 9.179317075224e9     
 4.609415861073477e10 
 4.064160273597923e10 
 2.9230639648809387e10
 2.866930795707619e10 
 1.8036110584894444e10
 1.793703289113461e10 
 2.6711999501520096e10

In [7]:
prices

618-element Array{Union{Missing, Float64},1}:
  46.689999
  46.689999
 169.119995
 169.119995
 169.119995
 115.82    
 115.82    
  62.619999
  78.190002
  78.190002
  38.41    
  38.41    
 102.949997
   ⋮       
  57.73    
   8.73    
   8.73    
  49.52    
  49.52    
  38.669998
  38.669998
  63.330002
  63.330002
 103.199997
 103.199997
  53.529999

In [8]:
# NOTE: must have either Gurobi or Mosek installed!

# Solve the LEAST SQUARES polynomial fit

using JuMP, Mosek, Ipopt, Gurobi

#m = Model(solver=ClpSolver())
#m = Model(solver=MosekSolver(LOG=0))
m = Model(solver=GurobiSolver(OutputFlag=0,BarHomogeneous=1))
#m = Model(solver=GurobiSolver(OutputFlag=0,NumericFocus=3,BarHomogeneous=1))
#m = Model(solver=IpoptSolver())

@variable(m, u[1:74])
@objective(m, Min, 1/1000000000000000 * sum( (y - B*u).^2 ) )

status = solve(m)
uopt = getvalue(u)
println(status)
println(getobjectivevalue(m))
println(uopt)

Academic license - for non-commercial use only


┌ Warning: Not solved to optimality, status: Suboptimal
└ @ JuMP C:\Users\Cole\.julia\packages\JuMP\PbnIJ\src\solvers.jl:212


Suboptimal
6.267481521346522e16
[4.15964e10, 3.47657, -12.0542, -6.92468e6, 244.425, 2.96782, -2.62467e7, 378.213, -2.11961, 0.845962, -71.563, -2.39576e7, 48.0921, -6.23396, -6.65616, 5035.8, -5063.27, 11.4792, 14.2783, 40.4684, 40.1743, 2.1197e7, -71.0387, 20.5538, 41.5635, -5077.17, 373.877, 246.904, 9.19397, -1.89107, 39.2348, -3.70191, -18.9436, -6.99052, 8.28763, -5.64629, -5.6136, -258.376, -148.846, 8.41653, 149.869, 19.7467, 373.645, -6.59734, 10.3536, -1.82228e9, 47.9974, 372.053, 4.15964e10, 1.34134, -4.7154, 249.764, -4.10841, 0.747197, -9.23461, 1.78092e9, 7.83986e5, 2.05741e8, 6.57875e7, -1.17835, 0.934228, 0.619567, 0.205784, 4.15964e10, 378.216, -44.5165, -335.364, -4.15964e10, -135.773, -130.186, 138.708, 71.4084, 0.302446, 2.84786e7]


In [9]:
save = uopt

74-element Array{Float64,1}:
    4.159642262945208e10 
    3.476573224258896    
  -12.054232260533272    
   -6.924681916698182e6  
  244.42504325392164     
    2.9678151193203233   
   -2.6246657364763014e7 
  378.2129286787726      
   -2.119610169724268    
    0.8459622909254283   
  -71.56295675572038     
   -2.3957600378346607e7 
   48.09208839160924     
    ⋮                    
    0.20578411703894517  
    4.1596422630917336e10
  378.21577952661494     
  -44.51647882405516     
 -335.36427100097205     
   -4.159642263321245e10 
 -135.7734237444554      
 -130.18554995115963     
  138.70807829194442     
   71.40841605626262     
    0.3024462272130988   
    2.847855663690381e7  

In [11]:
test = "./nyse/Fundamentals with Ratios FINAL/fundementals_with_ratios_testing_set.csv"
raw2 = CSV.read(test)

raw2

307×78 DataFrames.DataFrame. Omitted printing of 74 columns
│ Row │ Ticker Symbol │ Period Ending │ Accounts Payable │ Accounts Receivable │
│     │ String⍰       │ Dates…⍰       │ Int64⍰           │ Int64⍰              │
├─────┼───────────────┼───────────────┼──────────────────┼─────────────────────┤
│ 1   │ AAL           │ 2014-12-31    │ 4668000000       │ -160000000          │
│ 2   │ AAPL          │ 2014-09-27    │ 48649000000      │ -6452000000         │
│ 3   │ ABC           │ 2014-09-30    │ 17250160000      │ -938286000          │
│ 4   │ ABT           │ 2014-12-31    │ 5350000000       │ -195000000          │
│ 5   │ ADBE          │ 2014-11-28    │ 776163000        │ 7928000             │
│ 6   │ ADI           │ 2014-11-01    │ 430621000        │ -36460000           │
│ 7   │ ADM           │ 2014-12-31    │ 15240000000      │ 425000000           │
│ 8   │ ADS           │ 2014-12-31    │ 914058000        │ -156003000          │
│ 9   │ ADSK          │ 2014-01-31    │ 375300000        │ 72300000            │
│ 10  │ AEE           │ 2014-12-31    │ 842000000        │ 31000000            │
⋮
│ 297 │ WYN           │ 2014-12-31    │ 1134000000       │ -250000000          │
│ 298 │ WYNN          │ 2014-12-31    │ 728686000        │ 38000               │
│ 299 │ XEC           │ 2014-12-31    │ 740552000        │ -35133000           │
│ 300 │ XEL           │ 2014-12-31    │ 1879877000       │ -166408000          │
│ 301 │ XLNX          │ 2014-03-29    │ 369260000        │ -38658000           │
│ 302 │ XOM           │ 2014-12-31    │ 47165000000      │ 3118000000          │
│ 303 │ XRAY          │ 2014-12-31    │ 540800000        │ 7200000             │
│ 304 │ XRX           │ 2014-12-31    │ 2338000000       │ 67000000            │
│ 305 │ YHOO          │ 2014-12-31    │ 4178020000       │ 29278000            │
│ 306 │ YUM           │ 2014-12-27    │ 2142000000       │ -21000000           │
│ 307 │ ZBH           │ 2014-12-31    │ 225500000        │ -40400000           │

In [48]:
AAPL = raw2[302,3:76]

DataFrameRow. Omitted printing of 71 columns
│ Row │ Accounts Payable │ Accounts Receivable │ Add'l income/expense items │
│     │ Int64⍰           │ Int64⍰              │ Union{Missing, Int64}      │
├─────┼──────────────────┼─────────────────────┼────────────────────────────┤
│ 302 │ 47165000000      │ 3118000000          │ 4511000000                 │

In [49]:
using LinearAlgebra
AAPL = convert(Array, AAPL)

┌ Warning: `convert(::Type{Array}, dfr::DataFrameRow)` is deprecated, use `permutedims(Vector(dfr))` instead.
│   caller = top-level scope at In[49]:2
└ @ Core In[49]:2


1×74 Array{Any,2}:
 47165000000  3118000000  4511000000  19  …  3.49e11  3.94e11  -2.26e11  7.6

In [53]:
AAPL_Test = AAPL * save

1-element Array{Any,1}:
 4.078281678041825e11

In [54]:
AAPL_shares = raw2[302,77]

4.278947368e9

In [55]:
AAPL_price = raw2[302, 78]

92.449997

In [56]:
AAPL_shares * AAPL_price

3.955886713347579e11

In [57]:
AAPL_Test/AAPL_shares

1-element Array{Float64,1}:
 95.31039592917529