In [1]:
using CSV
file = "./nyse/Fundamentals with Ratios FINAL/fundementals_with_ratios_training_set.csv"
raw = CSV.read(file);

raw

618×78 DataFrames.DataFrame. Omitted printing of 74 columns
│ Row │ Ticker Symbol │ Period Ending │ Accounts Payable │ Accounts Receivable │
│     │ String⍰       │ String⍰       │ Int64⍰           │ Int64⍰              │
├─────┼───────────────┼───────────────┼──────────────────┼─────────────────────┤
│ 1   │ AAL           │ 31/12/12      │ 3068000000       │ -222000000          │
│ 2   │ AAL           │ 31/12/13      │ 4975000000       │ -93000000           │
│ 3   │ AAP           │ 29/12/12      │ 2409453000       │ -89482000           │
│ 4   │ AAP           │ 28/12/13      │ 2609239000       │ -32428000           │
│ 5   │ AAP           │ 02/01/16      │ 3757085000       │ -21476000           │
│ 6   │ AAPL          │ 28/09/13      │ 36223000000      │ -1949000000         │
│ 7   │ AAPL          │ 24/09/16      │ 59321000000      │ 1044000000          │
│ 8   │ ABBV          │ 31/12/13      │ 6448000000       │ 681000000           │
│ 9   │ ABC           │ 30/09/13      │ 14870635000      │ -2312518000         │
│ 10  │ ABC           │ 30/09/16      │ 24670159000      │ -912724000          │
⋮
│ 608 │ XRX           │ 31/12/12      │ 2654000000       │ 641000000           │
│ 609 │ XRX           │ 31/12/13      │ 2360000000       │ 573000000           │
│ 610 │ XYL           │ 31/12/12      │ 775000000        │ 2000000             │
│ 611 │ XYL           │ 31/12/13      │ 811000000        │ -47000000           │
│ 612 │ YHOO          │ 31/12/12      │ 993306000        │ 34752000            │
│ 613 │ YHOO          │ 31/12/13      │ 1045813000       │ 26199000            │
│ 614 │ YUM           │ 29/12/12      │ 2269000000       │ -18000000           │
│ 615 │ YUM           │ 28/12/13      │ 2194000000       │ -12000000           │
│ 616 │ ZBH           │ 31/12/12      │ 206900000        │ -45500000           │
│ 617 │ ZBH           │ 31/12/13      │ 367500000        │ -74300000           │
│ 618 │ ZTS           │ 31/12/13      │ 1381000000       │ -99000000           │

In [9]:
raw[:,78]

618-element Array{Union{Missing, Float64},1}:
  46.689999
  46.689999
 169.119995
 169.119995
 169.119995
 115.82    
 115.82    
  62.619999
  78.190002
  78.190002
  38.41    
  38.41    
 102.949997
   ⋮       
  57.73    
   8.73    
   8.73    
  49.52    
  49.52    
  38.669998
  38.669998
  63.330002
  63.330002
 103.199997
 103.199997
  53.529999

In [6]:
A = []

for i in 3:76
    push!(A, raw[:,i])
end

A

74-element Array{Any,1}:
 Union{Missing, Int64}[3068000000, 4975000000, 2409453000, 2609239000, 3757085000, 36223000000, 59321000000, 6448000000, 14870635000, 24670159000  …  2360000000, 775000000, 811000000, 993306000, 1045813000, 2269000000, 2194000000, 206900000, 367500000, 1381000000]        
 Union{Missing, Int64}[-222000000, -93000000, -89482000, -32428000, -21476000, -1949000000, 1044000000, 681000000, -2312518000, -912724000  …  573000000, 2000000, -47000000, 34752000, 26199000, -18000000, -12000000, -45500000, -74300000, -99000000]                        
 Union{Missing, Int64}[-1961000000, -2723000000, 600000, 2698000, -7484000, 1156000000, 1348000000, -54000000, -44000, 5048000  …  0, 0, -10000000, 4647839000, 123307000, 0, 0, 15600000, 9600000, 9000000]                                                                    
 Union{Missing, Int64}[23, 67, 32, 26, 19, 30, 36, 92, 19, 67  …  9, 14, 10, 27, 10, 74, 50, 13, 12, 54]                                                    

In [7]:
B = zeros(length(A),length(A[1]))

for i in 1:length(A)
    for j in 1:length(A[i])
        B[i,j] = A[i][j]
    end
end

In [8]:
B = B'
B

618×74 LinearAlgebra.Adjoint{Float64,Array{Float64,2}}:
 3.068e9     -2.22e8          -1.961e9    …  2.4855e10   -3.67e8      -5.6 
 4.975e9     -9.3e7           -2.723e9       2.6743e10    0.0        -11.25
 2.40945e9   -8.9482e7    600000.0           6.205e9     -2.7095e7     5.29
 2.60924e9   -3.2428e7         2.698e6       6.49381e9   -1.0789e8     5.36
 3.75709e9   -2.1476e7        -7.484e6       9.73702e9   -1.19709e8    6.45
 3.6223e10   -1.949e9          1.156e9    …  1.71e11      0.0         40.03
 5.9321e10    1.044e9          1.348e9       2.16e11      0.0          8.35
 6.448e9      6.81e8          -5.4e7         1.879e10    -3.2e8        2.58
 1.48706e10  -2.31252e9   -44000.0           8.79592e10  -1.51686e9    1.88
 2.46702e10  -9.12724e8        5.048e6       1.47e11     -4.39601e9    6.73
 1.0889e10    3.6e7           -1.26e9     …  1.905e10    -5.591e9      3.76
 5.948e9     -1.13e8           5.3e7         1.9657e10   -6.844e9      1.64
 7.29257e8    3.3649e7    926000

In [10]:
prices = raw[:78]
shares = raw[:77]

mkt_cap = prices.*shares
y = mkt_cap

618-element Array{Float64,1}:
 1.5641149665e10      
 7.611507391495777e9  
 1.239371426576783e10 
 1.2360841603946102e10
 1.2412568588116007e10
 1.07160263303394e11  
 6.337087832349199e11 
 1.001919984e11       
 1.8038059150222427e10
 1.6589862019528402e10
 6.0914582434549995e10
 6.0331804865869995e10
 5.147233599688258e10 
 ⋮                    
 8.218652729372e9     
 1.159150000194e10    
 1.087964516007e10    
 9.19215e9            
 9.179317075224e9     
 4.609415861073477e10 
 4.064160273597923e10 
 2.9230639648809387e10
 2.866930795707619e10 
 1.8036110584894444e10
 1.793703289113461e10 
 2.6711999501520096e10

In [11]:
prices

618-element Array{Union{Missing, Float64},1}:
  46.689999
  46.689999
 169.119995
 169.119995
 169.119995
 115.82    
 115.82    
  62.619999
  78.190002
  78.190002
  38.41    
  38.41    
 102.949997
   ⋮       
  57.73    
   8.73    
   8.73    
  49.52    
  49.52    
  38.669998
  38.669998
  63.330002
  63.330002
 103.199997
 103.199997
  53.529999

In [16]:
# NOTE: must have either Gurobi or Mosek installed!

# Solve the LEAST SQUARES polynomial fit

using JuMP, Mosek, Ipopt, Gurobi

#m = Model(solver=ClpSolver())
#m = Model(solver=MosekSolver(LOG=0))
#m = Model(solver=GurobiSolver(OutputFlag=0,BarHomogeneous=1))
#m = Model(solver=GurobiSolver(OutputFlag=0,NumericFocus=3,BarHomogeneous=1))
#m = Model(solver=IpoptSolver())

@variable(m, u[1:74])
@objective(m, Min, 1/10000000sum( (y - B*u).^2 ) )

status = solve(m)
uopt = getvalue(u)
println(status)
println(getobjectivevalue(m))
println(uopt)

┌ Info: Recompiling stale cache file /Users/ritik/.juliapro/JuliaPro_v1.0.3.1/compiled/v1.0/Gurobi/do9v6.ji for Gurobi [2e9cd046-0924-5485-92f1-d5272153d98b]
└ @ Base loading.jl:1190
ERROR: LoadError: Gurobi not properly installed. Please run Pkg.build("Gurobi")
Stacktrace:
 [1] error(::String) at /Applications/JuliaPro-1.0.3.1.app/Contents/Resources/julia/Contents/Resources/julia/lib/julia/sys.dylib:?
 [2] top-level scope at /Users/ritik/.juliapro/JuliaPro_v1.0.3.1/packages/Gurobi/jk68E/src/Gurobi.jl:8
 [3] include_relative(::Module, ::String) at /Applications/JuliaPro-1.0.3.1.app/Contents/Resources/julia/Contents/Resources/julia/lib/julia/sys.dylib:?
 [4] include(::Module, ::String) at /Applications/JuliaPro-1.0.3.1.app/Contents/Resources/julia/Contents/Resources/julia/lib/julia/sys.dylib:?
 [5] top-level scope at none:2
 [6] eval at ./boot.jl:319 [inlined]
 [7] eval(::Expr) at ./client.jl:393
 [8] top-level scope at ./none:3
in expression starting at /Users/ritik/.juliapro/JuliaPro_

ErrorException: Failed to precompile Gurobi [2e9cd046-0924-5485-92f1-d5272153d98b] to /Users/ritik/.juliapro/JuliaPro_v1.0.3.1/compiled/v1.0/Gurobi/do9v6.ji.