In [78]:
using CSV

raw = CSV.read("fundamentals copy.csv");

raw

3×79 DataFrames.DataFrame. Omitted printing of 75 columns
│ Row │ Column1 │ Ticker Symbol │ Period Ending │ Accounts Payable │
│     │ Int64⍰  │ String⍰       │ String⍰       │ Int64⍰           │
├─────┼─────────┼───────────────┼───────────────┼──────────────────┤
│ 1   │ 8       │ AAPL          │ 28/09/13      │ 36223000000      │
│ 2   │ 9       │ AAPL          │ 27/09/14      │ 48649000000      │
│ 3   │ 10      │ AAPL          │ 26/09/15      │ 60671000000      │

In [79]:
A = []

for i in 4:77
    push!(A, raw[:,i])
end

A

74-element Array{Any,1}:
 Union{Missing, Int64}[36223000000, 48649000000, 60671000000] 
 Union{Missing, Int64}[-1949000000, -6452000000, -3124000000] 
 Union{Missing, Int64}[1156000000, 980000000, 1285000000]     
 Union{Missing, Int64}[30, 35, 45]                            
 Union{Missing, Int64}[-8165000000, -9571000000, -11247000000]
 Union{Missing, Int64}[0, 0, 0]                               
 Union{Missing, Int64}[93, 40, 52]                            
 Union{Missing, Int64}[14259000000, 13844000000, 21120000000] 
 Union{Missing, Int64}[-973000000, -76000000, -238000000]     
 Union{Missing, Int64}[19764000000, 23313000000, 27416000000] 
 Union{Missing, Float64}[1.07e11, 1.12e11, 1.4e11]            
 Union{Missing, Int64}[168, 108, 111]                         
 Union{Missing, Int64}[0, 0, 0]                               
 ⋮                                                            
 Union{Missing, Int64}[10830000000, 11993000000, 14329000000] 
 Union{Missing, Int64}[0, 6308

In [80]:
B = zeros(length(A),length(A[1]))

for i in 1:length(A)
    for j in 1:length(A[i])
        B[i,j] = A[i][j]
    end
end

In [81]:
B = B'
B

3×74 LinearAlgebra.Adjoint{Float64,Array{Float64,2}}:
 3.6223e10  -1.949e9  1.156e9  30.0  …  2.07e11  1.71e11  0.0  40.03
 4.8649e10  -6.452e9  9.8e8    35.0     2.32e11  1.83e11  0.0   6.49
 6.0671e10  -3.124e9  1.285e9  45.0     2.9e11   2.34e11  0.0   9.28

In [82]:
prices = raw[:79]
shares = raw[:78]

mkt_cap = prices.*shares
y = mkt_cap

3-element Array{Float64,1}:
 6.394404028380046e11
 6.005641878492048e11
 6.491858972715176e11

In [83]:
prices

3-element Array{Union{Missing, Float64},1}:
  69.11142729
  98.650002  
 112.830002  

In [95]:
# NOTE: must have either Gurobi or Mosek installed!

# Solve the LEAST SQUARES polynomial fit

using JuMP, Mosek

#m = Model(solver=ClpSolver())
m = Model(solver=MosekSolver(LOG=0))
#m = Model(solver=GurobiSolver(OutputFlag=0,BarHomogeneous=1))
#m = Model(solver=GurobiSolver(OutputFlag=0,NumericFocus=3,BarHomogeneous=1))

@variable(m, u[1:74])
@objective(m, Min, sum( (y - B*u).^2 ) )

status = solve(m)
uopt = getvalue(u)
println(status)
println(getobjectivevalue(m))
println(uopt)

ErrorException: error compiling constructvariable!: error compiling Type: error compiling addvar!: error compiling updatemodel!: could not load library "libgurobi81.dylib"
dlopen(libgurobi81.dylib, 1): image not found