In [22]:
import numpy as np
import pandas as pd

a = np.genfromtxt('./nyse/prices-split-adjusted.csv', delimiter=',')
b = pd.read_csv('./nyse/prices-split-adjusted.csv')

In [318]:
c = b.loc[b['symbol']=="AAPL"] #filter by company symbol

In [301]:
d = c['close'].values #store close values as np array in d

d_shifted = np.roll(d, -1) #shift values left by 1
d_shifted

array([ 30.62571329,  30.13857071,  30.08285714, ..., 116.730003  ,
       115.82      ,  30.57285686])

In [302]:
d

array([ 30.57285686,  30.62571329,  30.13857071, ..., 116.760002  ,
       116.730003  , 115.82      ])

In [303]:
e = ((d_shifted/d)-1)*100 #calculate daily percent return 
# (day 2 / day1) - 1 ) *100

In [304]:
e = e[:-1] #remove last element to counteract shift
e

array([ 0.17288678, -1.59063257, -0.18485804, ..., -0.42640286,
       -0.02569287, -0.77957935])

In [305]:
np.average(e) #average expected return

0.08931506012020034

In [306]:
e.argmax()
d[582]

87.1428604285

In [307]:
np.std(e)

1.6512968004277009

In [308]:
np.split(e, [3])

[array([ 0.17288678, -1.59063257, -0.18485804]),
 array([ 0.66483284, -0.88215962, -1.13750034, ..., -0.42640286,
        -0.02569287, -0.77957935])]

In [309]:
f = e.reshape(-1,3)
np.average(f)

0.08931506012020034

In [310]:
sum = 0
num = 0
for i in f[0:]:
    print(i)
    print(np.std(i))
    sum = sum + np.std(i)
    num+=1

[ 0.17288678 -1.59063257 -0.18485804]
0.7611529204211955
[ 0.66483284 -0.88215962 -1.13750034]
0.7962962499695906
[ 1.41055314 -0.57916069 -1.67120279]
1.2757889360877985
[ 4.42383091 -1.53924622 -1.72861852]
2.8567033229751053
[-4.95986745  2.6902665   1.41330525]
3.346183724241643
[ 0.94202389 -4.13219636 -3.62787505]
2.282445748429595
[1.39018794 0.58029015 1.72061526]
0.47905671212204753
[-3.60387051  1.77557821 -0.68556431]
2.198792650040744
[ 1.06635433 -0.54538813  1.81938647]
0.9864036852842656
[ 0.86072334  1.50713799 -0.41789234]
0.799892473083041
[ 0.18760553 -0.62090475 -0.61982547]
0.3808812659865825
[-1.67647745  1.8268558   0.66779827]
1.4572571960510436
[ 1.29702621  2.13566957 -0.06699076]
0.9077185998233676
[0.22982906 0.65924856 3.91058891]
1.6432896595742859
[0.05936926 1.79843441 0.81606536]
0.7119601684666723
[ 0.29354875  0.48780397 -1.21800968]
0.7624772630052343
[ 0.27251653 -0.14702339  0.23648001]
0.1898500107787696
[-1.06832939  1.12486119  1.60622422]
1.164

[ 4.28889246 -1.75359896 -0.99665305]
2.6878669974691385
[ 2.78210038 -1.92324463  2.19700223]
2.0938811807117665
[1.45687039 0.96313721 0.84121153]
0.2661816749861061
[ 0.11180341 -2.13899658 -0.41257111]
0.9615735996183324
[ 1.55134601 -1.57104159  0.8112857 ]
1.3321860434871984
[ 0.59482155 -0.25217478 -1.97890072]
1.070982499424047
[-3.00605117  1.13699342 -0.65276607]
1.696598174821877
[0.73005565 0.36238631 0.47842481]
0.15346507371006798
[-0.47614681 -1.15544233  2.3926968 ]
1.5377110465466663
[-0.46379324  0.17025359 -1.41336612]
0.6507735063674245
[ 1.49714365 -0.73305917  0.62139949]
0.9174415353474022
[ 1.82582471 -0.00878527  1.52953408]
0.8041564467682041
[ 3.09956883 -3.19113448 -0.63323734]
2.5830564970450127
[ 4.12046606  1.0564283  -0.85455821]
2.0491478816920816
[ 1.40585774  1.14705397 -0.46504039]
0.8277202557575839
[-0.88524754  0.11577903 -0.40475633]
0.40877636624624847
[-3.1516986  -0.56521026 -0.33588838]
1.2767709990657448
[-2.92084771  1.63788861 -0.42914521]

In [311]:
sum/num

1.111850655373225

In [312]:
def reshape_weekly(array):
    size = array.size
    new_size = size - (size%7) #To make it divisible by 7
    array = array[:new_size] #trim last elements to make it divisible by 7
    return array.reshape(-1,7)

In [313]:
f = reshape_weekly(f.reshape(-1,1))
f

array([[ 0.17288678, -1.59063257, -0.18485804, ..., -0.88215962,
        -1.13750034,  1.41055314],
       [-0.57916069, -1.67120279,  4.42383091, ..., -1.72861852,
        -4.95986745,  2.6902665 ],
       [ 1.41330525,  0.94202389, -4.13219636, ...,  1.39018794,
         0.58029015,  1.72061526],
       ...,
       [ 0.50345948, -0.19679846, -0.09859371, ..., -0.93195714,
         0.37446708, -0.7188362 ],
       [ 0.7698616 ,  0.98226651,  0.98172026, ..., -0.57042037,
         1.66813676,  0.        ],
       [ 0.54692073,  0.12951217,  0.57773389, ...,  0.09405815,
        -0.65777978,  0.19777797]])

In [314]:
temp2 = f.reshape(-1,1)
temp2

array([[ 0.17288678],
       [-1.59063257],
       [-0.18485804],
       ...,
       [ 0.09405815],
       [-0.65777978],
       [ 0.19777797]])

In [315]:
temp1 #MSFT

array([[ 0.03230371],
       [-0.61369188],
       [-1.03997075],
       ...,
       [ 0.        ],
       [ 0.01573497],
       [-0.48780017]])

In [316]:
temp2

array([[ 0.17288678],
       [-1.59063257],
       [-0.18485804],
       ...,
       [ 0.09405815],
       [-0.65777978],
       [ 0.19777797]])

In [320]:
np.cov(np.transpose(temp1), np.transpose(temp2), bias=True)

array([[2.13628087, 0.94143461],
       [0.94143461, 2.73223051]])